### ISSUE TITLE
Folders with []

### ISSUE THREAD

**Issue by ghost** [mediaelch/mediaelch-dev#3]
For movies I observed the following behaviour:
if a moviefolder contains " [DVD] " for example it is ignored, if it contains " [BD] " it is not ignored.
Can this behaviour changed or is there a setting where I can configure what is ignored and what not?

ciao
Andreas

**Comment by bugwelle** [comment]
Hi Andreas,

sorry that I missed your issue. The main repository is in https://github.com/Komet/MediaElch/
I've copied/moved your issue to https://github.com/Komet/MediaElch/issues/1836

Regards,
Andre

**Comment by bugwelle** [comment]
Copied answer:

@adminsend MediaElch strips any "uneccessary" words from a movie's title.

"dvd" is part of the default set of words. You can remove/add words from MediaElch's settings in the settings dialog:
<img width="1072" alt="Screenshot 2024-12-22 at 12 59 58" src="https://github.com/user-attachments/assets/aad576ab-16e0-4dbb-80ce-a0dbc0479fe0" />
